name: java ci 
on:
  push:
    branches: [main]
jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Buld java package
      run: mvn clean install -f javarepo1/pom.xml
