name: Manual Java Build

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment to build for'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Print workflow
        run: echo "You triggered the ${{ GITHUB.WORKFLOW }}."
    
      - name: Print environment
        run: echo "You selected the ${{ github.event.inputs.environment }} environment."

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build Java App
        run: mvn -B clean install -f Javarepo1/pom.xml

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-java-artifact
          path: Javarepo1/target/*.jar
