name: Multi-Job Java CI Demo

on:
  push:
    branches: [ main ]

jobs:
  # 1️⃣ Build Job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build Project
        run: mvn -B compile -f Javarepo1/pom.xml

      - name: Upload Compiled Classes
        uses: actions/upload-artifact@v4
        with:
          name: compiled-classes
          path: Javarepo1/target/
           # 2️⃣ Test Job (depends on build)
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Download Compiled Classes
        uses: actions/download-artifact@v4
        with:
          name: compiled-classes
          path: Javarepo1/target/

      - name: Run Unit Tests
        run: mvn test -f Javarepo1/pom.xml

  # 3️⃣ Deploy Job (only if tests pass)
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Pretend Deploy
        run: echo "🚀 Deployment step would go here!"
